/**
 * Copyright (c) 2025 GregTech-6 Team
 *
 * This file is part of GregTech.
 *
 * GregTech is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * GregTech is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with GregTech. If not, see <http://www.gnu.org/licenses/>.
 */

package gregapi.compat.gt5u;

import static gregapi.data.CS.*;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import net.minecraftforge.oredict.OreDictionary;

import gregapi.data.CS.ConfigsGT;
import gregapi.oredict.OreDictMaterial;
import gregapi.oredict.OreDictPrefix;

/**
 * Hands the Material Variants that GregTech 5 already has over to GregTech 5.
 * <p>
 * A Material is more than its name: it comes as a whole family of Variants, one per OrePrefix. When both GregTechs
 * are installed, a shared Material would otherwise exist twice for every Prefix the two have in common, which is two
 * Items competing for the same OreDictionary entry and two entries in every Recipe Viewer.
 * <p>
 * So for every shared Material and every Prefix GregTech 5 provides that Variant for, GregTech 6 stops generating its
 * own. The Materials that only GregTech 5 has take part in the same way, since {@link GT5UMaterialBridge} gives them a
 * GregTech 6 Material of their own. Nothing has to be special cased for the Variants GregTech 5 does not have, because
 * those keep being generated by GregTech 6, which is the whole point: the Ladders, Chests and whatever else GregTech 5
 * never had still show up, for its own Materials just as much as for the shared ones.
 * <p>
 * <ul>
 * <li>{@link #getHandedOverPairs()} counts the Variants that are GregTech 5's job from now on,</li>
 * <li>{@link #getAddedPairs()} counts the Variants GregTech 6 still adds on top,</li>
 * <li>{@link #getMissingPairs()} counts the Variants GregTech 5 claims but does not actually register, which
 * GregTech 6 therefore keeps generating,</li>
 * <li>{@link #getPrefixesWithOwnVariants()} names the Prefixes that still contribute those additions.</li>
 * </ul>
 * Resolving a Prefix and Material to an ItemStack prefers the OreDictionary, so every Recipe that asks for e.g. an
 * Iron Ingot gets the GregTech 5 one without any further change, and if GregTech 5 is absent the generation is left
 * completely alone.
 * <p>
 * A Variant is only handed over when the OreDictionary really has the entry, and not merely because GregTech 5 reports
 * that it generates it. That check is what keeps a Recipe from being left without its Output: GregTech 5 claims e.g.
 * the empty Bullet Casings but does not actually register them, and without this GregTech 6 would have stopped making
 * them.
 */
public class GT5UMaterialVariants {

    private static final List<String> PREFIXES_WITH_OWN_VARIANTS = new ArrayList<>();
    private static int HANDED_OVER_PAIRS = 0, ADDED_PAIRS = 0, MISSING_PAIRS = 0, CREATED_MATERIAL_PAIRS = 0;
    private static boolean APPLIED = false;

    /**
     * Hands over every Variant GregTech 5 provides. Does nothing if GregTech 5 is absent or if its Material Table
     * cannot be read, and repeated calls are no-ops.
     */
    public static void apply() {
        if (APPLIED) return;
        APPLIED = true;
        if (!GT5UMaterialSource.isAvailable()) return;

        // Registering an Item means registering an OreDictionary entry, and every Mod that reacts to those pays for
        // each one. GregTech 5 does exactly that, so the Variants that are left to GregTech 5 are the single biggest
        // lever on the startup time of a Pack that has both Mods.
        boolean tOnlyExtrasForOwnMaterials = ConfigsGT.GREGTECH.get("general", "GT5UOnlyMaterialExtrasOnly", T);

        Map<String, GT5UMaterialSnapshot> tCreated = GT5UMaterialBridge.getCreated();
        for (OreDictPrefix tPrefix : OreDictPrefix.VALUES) {
            boolean tKeepsOwnVariants = false;
            for (String tName : names()) {
                OreDictMaterial tMaterial = OreDictMaterial.MATERIAL_MAP.get(tName);
                if (tMaterial == null || tMaterial.mID < 0) continue;
                if (tCreated.containsKey(tName)) {
                    // GregTech 5 does not have this Material at all. Its Variants are only added where GregTech 6
                    // brings a Prefix of its own, so the Material behaves like in GregTech 5 plus those extras.
                    if (tOnlyExtrasForOwnMaterials && GT5UMaterialSource.hasPrefix(tPrefix.mNameInternal)) {
                        tPrefix.disableItemGeneration(tMaterial);
                        HANDED_OVER_PAIRS++;
                    } else if (tPrefix.isGeneratingItem(tMaterial)) {
                        tKeepsOwnVariants = true;
                        CREATED_MATERIAL_PAIRS++;
                    }
                    continue;
                }
                if (!GT5UMaterialSource.doesGenerate(tPrefix.mNameInternal, tName)) {
                    if (tPrefix.isGeneratingItem(tMaterial)) {
                        tKeepsOwnVariants = true;
                        ADDED_PAIRS++;
                    }
                } else if (OreDictionary.getOres(tPrefix.mNameInternal + tName, false)
                    .isEmpty()) {
                        // GregTech 5 says it generates this one but the OreDictionary does not have it, so handing it
                        // over would leave Recipes without their Output.
                        if (tPrefix.isGeneratingItem(tMaterial)) {
                            tKeepsOwnVariants = true;
                            MISSING_PAIRS++;
                        }
                    } else {
                        tPrefix.disableItemGeneration(tMaterial);
                        HANDED_OVER_PAIRS++;
                    }
            }
            if (tKeepsOwnVariants) PREFIXES_WITH_OWN_VARIANTS.add(tPrefix.mNameInternal);
        }
    }

    /** Every Name that exists on both sides by now, no matter which of the two GregTechs it started in. */
    private static Set<String> names() {
        Set<String> rNames = new LinkedHashSet<>(
            GT5UMaterialBridge.getAdopted()
                .keySet());
        rNames.addAll(
            GT5UMaterialBridge.getCreated()
                .keySet());
        return rNames;
    }

    /** True once {@link #apply()} ran, whether or not GregTech 5 turned out to be present. */
    public static boolean isApplied() {
        return APPLIED;
    }

    /** How many Material Variants are generated by GregTech 5 instead of GregTech 6. */
    public static int getHandedOverPairs() {
        return HANDED_OVER_PAIRS;
    }

    /** How many Material Variants GregTech 6 still generates on top of what GregTech 5 has. */
    public static int getAddedPairs() {
        return ADDED_PAIRS;
    }

    /**
     * How many Material Variants GregTech 5 reports as generated but never registered, which is why GregTech 6 keeps
     * generating them.
     */
    public static int getMissingPairs() {
        return MISSING_PAIRS;
    }

    /** How many Material Variants of the Materials GregTech 5 does not have are generated by GregTech 6. */
    public static int getCreatedMaterialPairs() {
        return CREATED_MATERIAL_PAIRS;
    }

    /** The Prefixes whose Variants GregTech 6 still has to generate for the shared Materials. Sorted for output. */
    public static List<String> getPrefixesWithOwnVariants() {
        List<String> rPrefixes = new ArrayList<>(PREFIXES_WITH_OWN_VARIANTS);
        Collections.sort(rPrefixes);
        return Collections.unmodifiableList(rPrefixes);
    }
}
